production:
  path_install: D:\Business
  path_copy: D:\Copia
  upload_path: empresas/prueba
  folders:
    - source_folder: reportes
    - source_folder: repodos
    - source_folder: DEMO\datos
      destiny_folder: DB
  extensions:
    - .frx
    - .frt
    - .fpt
    - .cdx
    - .dbf
    - .bak